sudo: required
services: 
  - docker

before_install:
  - docker build -t testerdetest/dockercursus-react -f Dockerfile.dev .

script:
  - docker run testerdetest/dockercursus-react npm run test -- --coverage